version: "3"
services:
  test-container:
    env_file:
      - ../.env/.test.env
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: cerana-test-container
    command: sh -c "npm install --save-dev jest; npm run test"