version: "3"
services:
  local-container:
    env_file:
      - ../.env/.local.env
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: cerana-local-container
    command: sh -c "npm start"