name: Deploy Docker image to Google Compute Engine
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{vars.PROJECT_ID}}
  IMAGE_NAME: ${{vars.IMAGE_NAME}}
  INSTANCE_NAME: ${{vars.INSTANCE_NAME}}
  REGION: ${{vars.REGION}}

jobs:



  deploy:
  
  
    
    runs-on: ubuntu-latest
 
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code 
        uses: actions/checkout@v3


        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cerana-backend/${{ env.IMAGE_NAME }}:latest

      - name: Deploy Docker image to Google Compute Engine
        run: |
          gcloud compute instances update-container ${{ env.INSTANCE_NAME }} \
            --container-image=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cerana-backend/${{ env.IMAGE_NAME }}:latest \
            --zone=${{ env.REGION }}-b
            
      - name: Start Docker container on Compute Engine instance
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} --zone=${{ env.REGION }}-b --command='sudo docker run -d --name cerana-backend-container -p 8080:8080 us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cerana-backend/${{ env.IMAGE_NAME }}:latest'

      - name: Run command inside Docker container on Compute Engine instance
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} --zone=${{ env.REGION }}-b --command='sudo docker exec cerana-backend-container "npm start"'
          
          
          
          
          
          
          
