name: Deploy Docker image to Google Compute Engine
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{vars.PROJECT_ID}}
  IMAGE_NAME: ${{vars.IMAGE_NAME}}
  INSTANCE_NAME: ${{vars.INSTANCE_NAME}}
  REGION: ${{vars.REGION}}

jobs:



  deploy:
  
  
    
    runs-on: ubuntu-latest
    environment: google_CD
 
    steps:
    
      - name: print env
        run: echo "${{vars.PROJECT_ID}}" 
      
